// ============================================================
// UrbanGuard — Sample Data & State Management
// ============================================================

export const CATEGORIES = {
  pothole:       { label: 'Pothole / Road Damage',      icon: 'fa-road',              color: '#f59e0b', severity: 'medium' },
  water_leak:    { label: 'Water Leak / Supply',         icon: 'fa-droplet',           color: '#3b82f6', severity: 'high' },
  streetlight:   { label: 'Streetlight Out',             icon: 'fa-lightbulb',         color: '#8b5cf6', severity: 'low' },
  garbage:       { label: 'Garbage / Sanitation',        icon: 'fa-trash-can',         color: '#6b7280', severity: 'medium' },
  drainage:      { label: 'Drainage / Flooding',         icon: 'fa-water',             color: '#06b6d4', severity: 'high' },
  electricity:   { label: 'Electricity / Power',         icon: 'fa-bolt',              color: '#eab308', severity: 'high' },
  sidewalk:      { label: 'Sidewalk Damage',             icon: 'fa-person-walking',    color: '#f97316', severity: 'medium' },
  graffiti:      { label: 'Graffiti / Vandalism',        icon: 'fa-spray-can',         color: '#ec4899', severity: 'low' },
  noise:         { label: 'Noise Pollution',             icon: 'fa-volume-high',       color: '#a855f7', severity: 'low' },
  construction:  { label: 'Illegal Construction',        icon: 'fa-helmet-safety',     color: '#dc2626', severity: 'high' },
  tree_hazard:   { label: 'Tree / Branch Hazard',        icon: 'fa-tree',              color: '#22c55e', severity: 'medium' },
  traffic:       { label: 'Traffic Signal Issue',        icon: 'fa-traffic-light',     color: '#ef4444', severity: 'high' },
};

export const STATUSES = {
  reported:      { label: 'Reported',        color: '#6b7280', icon: 'fa-flag' },
  verified:      { label: 'Verified',        color: '#3b82f6', icon: 'fa-check-circle' },
  in_progress:   { label: 'In Progress',     color: '#f59e0b', icon: 'fa-spinner' },
  resolved:      { label: 'Resolved',        color: '#10b981', icon: 'fa-circle-check' },
  closed:        { label: 'Closed',          color: '#6366f1', icon: 'fa-lock' },
};

export const BADGES = [
  { id: 'first_report',   name: 'First Report',     icon: 'fa-flag',              desc: 'Submitted your first issue report',         xp: 50  },
  { id: 'reporter_5',     name: 'Vigilant Eye',      icon: 'fa-eye',               desc: 'Reported 5 issues',                         xp: 150 },
  { id: 'reporter_25',    name: 'Neighborhood Watch', icon: 'fa-shield-halved',    desc: 'Reported 25 issues',                        xp: 500 },
  { id: 'verifier_5',     name: 'Truth Seeker',      icon: 'fa-magnifying-glass',  desc: 'Verified 5 community issues',               xp: 200 },
  { id: 'verifier_20',    name: 'Fact Checker',      icon: 'fa-check-double',      desc: 'Verified 20 community issues',              xp: 600 },
  { id: 'resolver',       name: 'Problem Solver',    icon: 'fa-wrench',            desc: 'Had 10 issues resolved',                    xp: 400 },
  { id: 'streak_7',       name: 'Week Warrior',      icon: 'fa-fire',              desc: '7-day reporting streak',                    xp: 300 },
  { id: 'streak_30',      name: 'Monthly Maven',     icon: 'fa-fire-flame-curved', desc: '30-day reporting streak',                   xp: 1000 },
  { id: 'influencer',     name: 'Community Voice',   icon: 'fa-bullhorn',          desc: 'Got 50 upvotes on your reports',            xp: 500 },
  { id: 'early_bird',     name: 'Early Bird',        icon: 'fa-sun',               desc: 'Report an issue before 7 AM',               xp: 100 },
  { id: 'mapper',         name: 'Cartographer',      icon: 'fa-map',               desc: 'Report issues in 10 different areas',       xp: 350 },
  { id: 'champion',       name: 'City Champion',     icon: 'fa-crown',             desc: 'Reach Level 10',                            xp: 2000 },
];

export const LEVEL_THRESHOLDS = [0, 100, 250, 500, 850, 1300, 1900, 2650, 3600, 4800, 6300, 8200, 10500, 13300, 16700, 20800, 25800, 31800, 39000, 47800];

// ---- Sample Issues ----
export const SAMPLE_ISSUES = [
  {
    id: 'UG-1001',
    title: 'Large pothole on MG Road near City Mall',
    category: 'pothole',
    status: 'verified',
    description: 'A deep pothole approximately 2 feet wide has formed on MG Road, right in front of City Mall. Multiple vehicles have been damaged. The pothole fills with water during rain making it invisible and dangerous.',
    location: { lat: 12.9716, lng: 77.5946, address: 'MG Road, Bengaluru' },
    reportedBy: { name: 'Priya Sharma', avatar: 'PS', level: 5 },
    reportedAt: '2026-06-18T09:30:00',
    upvotes: 47,
    verifications: 8,
    images: ['pothole_mg_road.jpg'],
    priority: 'high',
    estimatedResolution: '2026-07-02',
    timeline: [
      { status: 'reported',  at: '2026-06-18T09:30:00', by: 'Priya Sharma' },
      { status: 'verified',  at: '2026-06-18T14:20:00', by: 'System AI + 3 citizens' },
    ],
    comments: [
      { user: 'Ravi K.', text: 'I damaged my car tyre here last week!', at: '2026-06-18T11:00:00' },
      { user: 'Meena D.', text: 'This is getting worse every day. Please fix ASAP.', at: '2026-06-19T08:15:00' },
    ],
  },
  {
    id: 'UG-1002',
    title: 'Water pipe burst on 5th Cross, Koramangala',
    category: 'water_leak',
    status: 'in_progress',
    description: 'A major water pipeline has burst on 5th Cross, Koramangala 4th Block. Water is flooding the street and several houses have been affected. BWSSB has been informed.',
    location: { lat: 12.9352, lng: 77.6245, address: '5th Cross, Koramangala, Bengaluru' },
    reportedBy: { name: 'Arjun Reddy', avatar: 'AR', level: 7 },
    reportedAt: '2026-06-20T06:45:00',
    upvotes: 62,
    verifications: 12,
    images: ['water_burst_kora.jpg'],
    priority: 'critical',
    estimatedResolution: '2026-06-25',
    timeline: [
      { status: 'reported',    at: '2026-06-20T06:45:00', by: 'Arjun Reddy' },
      { status: 'verified',    at: '2026-06-20T07:30:00', by: 'System AI + 5 citizens' },
      { status: 'in_progress', at: '2026-06-20T10:00:00', by: 'BWSSB Team #14' },
    ],
    comments: [
      { user: 'Sunita M.', text: 'Our basement is flooded! Need immediate help.', at: '2026-06-20T07:15:00' },
    ],
  },
  {
    id: 'UG-1003',
    title: 'Streetlight out on entire stretch of HSR Layout Sector 2',
    category: 'streetlight',
    status: 'reported',
    description: 'All 12 streetlights on the 17th Main Road in HSR Layout Sector 2 have been non-functional for over a week. The area is very dark at night and there have been safety concerns raised by residents.',
    location: { lat: 12.9116, lng: 77.6474, address: '17th Main, HSR Layout, Bengaluru' },
    reportedBy: { name: 'Deepa Nair', avatar: 'DN', level: 3 },
    reportedAt: '2026-06-21T19:20:00',
    upvotes: 28,
    verifications: 4,
    images: ['streetlight_hsr.jpg'],
    priority: 'medium',
    estimatedResolution: null,
    timeline: [
      { status: 'reported', at: '2026-06-21T19:20:00', by: 'Deepa Nair' },
    ],
    comments: [],
  },
  {
    id: 'UG-1004',
    title: 'Garbage dump overflowing near Indiranagar Park',
    category: 'garbage',
    status: 'resolved',
    description: 'The garbage collection bin near Indiranagar 100ft Road Park has been overflowing for 3 days. Stray dogs are scattering waste and there is a foul smell. Residents are unable to use the park.',
    location: { lat: 12.9784, lng: 77.6408, address: '100ft Road, Indiranagar, Bengaluru' },
    reportedBy: { name: 'Vikram Patel', avatar: 'VP', level: 8 },
    reportedAt: '2026-06-15T08:00:00',
    upvotes: 34,
    verifications: 6,
    images: ['garbage_indira.jpg'],
    priority: 'medium',
    estimatedResolution: '2026-06-17',
    resolvedAt: '2026-06-17T11:30:00',
    timeline: [
      { status: 'reported',    at: '2026-06-15T08:00:00', by: 'Vikram Patel' },
      { status: 'verified',    at: '2026-06-15T10:45:00', by: 'System AI + 4 citizens' },
      { status: 'in_progress', at: '2026-06-16T09:00:00', by: 'BBMP Ward 58' },
      { status: 'resolved',    at: '2026-06-17T11:30:00', by: 'BBMP Ward 58' },
    ],
    comments: [
      { user: 'Nisha G.', text: 'Thank you for reporting! This was getting unbearable.', at: '2026-06-15T09:00:00' },
      { user: 'Vikram Patel', text: 'Confirmed resolved! Bin has been cleared and extra bins placed.', at: '2026-06-17T12:00:00' },
    ],
  },
  {
    id: 'UG-1005',
    title: 'Severe waterlogging during rain on Outer Ring Road',
    category: 'drainage',
    status: 'in_progress',
    description: 'Every time it rains, the Outer Ring Road stretch between Marathahalli and ITPB gets severely waterlogged. The drains are clogged and water reaches knee-deep. Traffic is disrupted for hours.',
    location: { lat: 12.9568, lng: 77.7011, address: 'Outer Ring Road, Marathahalli, Bengaluru' },
    reportedBy: { name: 'Karthik S.', avatar: 'KS', level: 6 },
    reportedAt: '2026-06-10T17:30:00',
    upvotes: 89,
    verifications: 21,
    images: ['flooding_orr.jpg'],
    priority: 'high',
    estimatedResolution: '2026-07-15',
    timeline: [
      { status: 'reported',    at: '2026-06-10T17:30:00', by: 'Karthik S.' },
      { status: 'verified',    at: '2026-06-11T08:00:00', by: 'System AI + 10 citizens' },
      { status: 'in_progress', at: '2026-06-14T11:00:00', by: 'BBMP Drainage Division' },
    ],
    comments: [
      { user: 'Amit T.', text: 'I got stuck here for 3 hours last rain. Absolute nightmare.', at: '2026-06-10T18:00:00' },
      { user: 'Sneha R.', text: 'The drains definitely need desilting. Urgent!', at: '2026-06-12T10:30:00' },
    ],
  },
  {
    id: 'UG-1006',
    title: 'Exposed electrical wire near Whitefield bus stop',
    category: 'electricity',
    status: 'verified',
    description: 'A live electrical wire is exposed near the Whitefield Main Bus Stop. Sparks were observed during morning rain. Extremely dangerous for commuters, especially children.',
    location: { lat: 12.9698, lng: 77.7500, address: 'Whitefield Main Bus Stop, Bengaluru' },
    reportedBy: { name: 'Lakshmi V.', avatar: 'LV', level: 4 },
    reportedAt: '2026-06-22T07:15:00',
    upvotes: 55,
    verifications: 9,
    images: ['electric_whitefield.jpg'],
    priority: 'critical',
    estimatedResolution: '2026-06-24',
    timeline: [
      { status: 'reported', at: '2026-06-22T07:15:00', by: 'Lakshmi V.' },
      { status: 'verified', at: '2026-06-22T08:00:00', by: 'System AI + 6 citizens' },
    ],
    comments: [
      { user: 'Ramesh P.', text: 'This is a life-threatening hazard! BESCOM needs to act immediately.', at: '2026-06-22T07:45:00' },
    ],
  },
  {
    id: 'UG-1007',
    title: 'Broken sidewalk on Church Street near restaurants',
    category: 'sidewalk',
    status: 'reported',
    description: 'The sidewalk tiles are broken and uneven along Church Street between two popular restaurants. Multiple people have tripped and one elderly person fell last week.',
    location: { lat: 12.9730, lng: 77.6040, address: 'Church Street, Bengaluru' },
    reportedBy: { name: 'Samuel J.', avatar: 'SJ', level: 2 },
    reportedAt: '2026-06-22T11:00:00',
    upvotes: 15,
    verifications: 3,
    images: ['sidewalk_church.jpg'],
    priority: 'medium',
    estimatedResolution: null,
    timeline: [
      { status: 'reported', at: '2026-06-22T11:00:00', by: 'Samuel J.' },
    ],
    comments: [],
  },
  {
    id: 'UG-1008',
    title: 'Graffiti vandalism on Jayanagar 4th Block bus shelter',
    category: 'graffiti',
    status: 'reported',
    description: 'The newly built bus shelter in Jayanagar 4th Block has been covered with graffiti and offensive stickers. This was just painted last month as part of the ward improvement project.',
    location: { lat: 12.9279, lng: 77.5835, address: 'Jayanagar 4th Block, Bengaluru' },
    reportedBy: { name: 'Anita R.', avatar: 'AR2', level: 3 },
    reportedAt: '2026-06-21T16:00:00',
    upvotes: 8,
    verifications: 2,
    images: ['graffiti_jaya.jpg'],
    priority: 'low',
    estimatedResolution: null,
    timeline: [
      { status: 'reported', at: '2026-06-21T16:00:00', by: 'Anita R.' },
    ],
    comments: [],
  },
  {
    id: 'UG-1009',
    title: 'Illegal construction blocking drainage in BTM Layout',
    category: 'construction',
    status: 'verified',
    description: 'A new commercial building is being constructed blocking the natural drainage path in BTM Layout 2nd Stage. This is causing water to stagnate and flood nearby houses during rain.',
    location: { lat: 12.9166, lng: 77.6101, address: 'BTM Layout 2nd Stage, Bengaluru' },
    reportedBy: { name: 'Rahul M.', avatar: 'RM', level: 9 },
    reportedAt: '2026-06-19T14:30:00',
    upvotes: 41,
    verifications: 7,
    images: ['construction_btm.jpg'],
    priority: 'high',
    estimatedResolution: '2026-07-10',
    timeline: [
      { status: 'reported', at: '2026-06-19T14:30:00', by: 'Rahul M.' },
      { status: 'verified', at: '2026-06-19T16:00:00', by: 'System AI + 4 citizens' },
    ],
    comments: [
      { user: 'Kavitha S.', text: 'This construction has no proper approvals. BBMP must act.', at: '2026-06-19T15:30:00' },
    ],
  },
  {
    id: 'UG-1010',
    title: 'Traffic signal malfunction at Silk Board Junction',
    category: 'traffic',
    status: 'in_progress',
    description: 'The traffic signal at Silk Board Junction has been malfunctioning since yesterday. All lights show green simultaneously, causing chaos during peak hours. Traffic police are manually managing but it is insufficient.',
    location: { lat: 12.9177, lng: 77.6238, address: 'Silk Board Junction, Bengaluru' },
    reportedBy: { name: 'Mohan D.', avatar: 'MD', level: 6 },
    reportedAt: '2026-06-21T08:00:00',
    upvotes: 73,
    verifications: 15,
    images: ['traffic_silk.jpg'],
    priority: 'critical',
    estimatedResolution: '2026-06-24',
    timeline: [
      { status: 'reported',    at: '2026-06-21T08:00:00', by: 'Mohan D.' },
      { status: 'verified',    at: '2026-06-21T08:30:00', by: 'System AI + 8 citizens' },
      { status: 'in_progress', at: '2026-06-21T12:00:00', by: 'Traffic Police + BTRCL' },
    ],
    comments: [
      { user: 'Swathi N.', text: 'Silk Board is already the worst junction. This makes it impossible!', at: '2026-06-21T09:00:00' },
    ],
  },
  {
    id: 'UG-1011',
    title: 'Fallen tree blocking road in Cubbon Park area',
    category: 'tree_hazard',
    status: 'resolved',
    description: 'A large tree branch has fallen completely blocking the road near Cubbon Park main entrance. It also damaged a parked car. Tree debris is scattered across the road.',
    location: { lat: 12.9763, lng: 77.5929, address: 'Cubbon Park, Bengaluru' },
    reportedBy: { name: 'Geetha K.', avatar: 'GK', level: 5 },
    reportedAt: '2026-06-16T06:30:00',
    upvotes: 22,
    verifications: 5,
    images: ['tree_cubbon.jpg'],
    priority: 'high',
    estimatedResolution: '2026-06-16',
    resolvedAt: '2026-06-16T14:00:00',
    timeline: [
      { status: 'reported',    at: '2026-06-16T06:30:00', by: 'Geetha K.' },
      { status: 'verified',    at: '2026-06-16T07:00:00', by: 'System AI + 3 citizens' },
      { status: 'in_progress', at: '2026-06-16T08:00:00', by: 'BBMP Forest Cell' },
      { status: 'resolved',    at: '2026-06-16T14:00:00', by: 'BBMP Forest Cell' },
    ],
    comments: [],
  },
  {
    id: 'UG-1012',
    title: 'Excessive noise from construction site in Hebbal',
    category: 'noise',
    status: 'reported',
    description: 'The high-rise construction near Hebbal Flyway operates heavy machinery well beyond permitted hours (10 PM to 6 AM). The noise is causing sleep disturbance for hundreds of residents.',
    location: { lat: 13.0358, lng: 77.5970, address: 'Hebbal Flyway, Bengaluru' },
    reportedBy: { name: 'Divya P.', avatar: 'DP', level: 4 },
    reportedAt: '2026-06-22T23:00:00',
    upvotes: 31,
    verifications: 6,
    images: ['noise_hebbal.jpg'],
    priority: 'medium',
    estimatedResolution: null,
    timeline: [
      { status: 'reported', at: '2026-06-22T23:00:00', by: 'Divya P.' },
    ],
    comments: [
      { user: 'Rajesh V.', text: 'They were hammering at 2 AM last night! This is unacceptable.', at: '2026-06-23T06:00:00' },
    ],
  },
];

// ---- Leaderboard Data ----
export const LEADERBOARD = [
  { rank: 1,  name: 'Rahul M.',     avatar: 'RM',  level: 9,  xp: 2650,  issues: 38, verifications: 42, badges: 8 },
  { rank: 2,  name: 'Arjun Reddy',   avatar: 'AR',  level: 7,  xp: 1900,  issues: 27, verifications: 35, badges: 7 },
  { rank: 3,  name: 'Karthik S.',    avatar: 'KS',  level: 6,  xp: 1480,  issues: 22, verifications: 28, badges: 6 },
  { rank: 4,  name: 'Vikram Patel',  avatar: 'VP',  level: 8,  xp: 2200,  issues: 31, verifications: 18, badges: 7 },
  { rank: 5,  name: 'Mohan D.',      avatar: 'MD',  level: 6,  xp: 1350,  issues: 19, verifications: 31, badges: 5 },
  { rank: 6,  name: 'Priya Sharma',  avatar: 'PS',  level: 5,  xp: 1050,  issues: 16, verifications: 22, badges: 5 },
  { rank: 7,  name: 'Geetha K.',     avatar: 'GK',  level: 5,  xp: 980,   issues: 14, verifications: 19, badges: 4 },
  { rank: 8,  name: 'Lakshmi V.',    avatar: 'LV',  level: 4,  xp: 750,   issues: 11, verifications: 15, badges: 4 },
  { rank: 9,  name: 'Divya P.',      avatar: 'DP',  level: 4,  xp: 680,   issues: 9,  verifications: 12, badges: 3 },
  { rank: 10, name: 'Deepa Nair',    avatar: 'DN',  level: 3,  xp: 480,   issues: 7,  verifications: 8,  badges: 3 },
  { rank: 11, name: 'Samuel J.',     avatar: 'SJ',  level: 2,  xp: 220,   issues: 4,  verifications: 3,  badges: 2 },
  { rank: 12, name: 'Anita R.',      avatar: 'AR2', level: 3,  xp: 450,   issues: 6,  verifications: 7,  badges: 2 },
];

// ---- Predictive Insights ----
export const PREDICTIONS = [
  {
    category: 'drainage',
    title: 'Flooding Risk Alert — East Zone',
    description: 'Based on monsoon patterns and current drainage blockage reports, 3 areas in East Zone have a 78% probability of severe flooding in the next 2 weeks.',
    confidence: 0.78,
    severity: 'high',
    areas: ['Marathahalli', 'Whitefield', 'KR Puram'],
  },
  {
    category: 'pothole',
    title: 'Pothole Surge Expected — South Zone',
    description: 'Recent rainfall combined with aging road infrastructure suggests a 65% increase in pothole reports in South Zone within the next month.',
    confidence: 0.65,
    severity: 'medium',
    areas: ['Jayanagar', 'JP Nagar', 'BTM Layout'],
  },
  {
    category: 'electricity',
    title: 'Power Outage Cluster — Central Zone',
    description: 'Analysis of age-related transformer failures and load patterns indicates 5 substations in Central Zone are at elevated risk of failure.',
    confidence: 0.71,
    severity: 'high',
    areas: ['MG Road', 'Church Street', 'Residency Road'],
  },
  {
    category: 'garbage',
    title: 'Collection Delays Predicted — North Zone',
    description: 'Staff shortage patterns and festival season waste generation models predict 40% longer garbage collection times in North Zone starting next week.',
    confidence: 0.59,
    severity: 'medium',
    areas: ['Hebbal', 'Yelahanka', 'Sahakara Nagar'],
  },
  {
    category: 'traffic',
    title: 'Signal Failure Hotspot — Outer Ring Road',
    description: 'Correlation between power fluctuation reports and traffic signal age suggests 3 junctions on ORR are likely to malfunction within 10 days.',
    confidence: 0.62,
    severity: 'medium',
    areas: ['Silk Board', 'Agara', 'Iblur'],
  },
];

// ---- Monthly Trend Data ----
export const MONTHLY_TRENDS = {
  labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun'],
  reported:    [145, 132, 168, 189, 210, 198],
  resolved:    [120, 118, 155, 170, 195, 180],
  avgResolutionDays: [8.2, 7.5, 6.8, 7.1, 6.3, 5.9],
  categories: {
    pothole:     [32, 28, 35, 42, 48, 45],
    water_leak:  [18, 15, 22, 25, 28, 30],
    streetlight: [12, 14, 10, 15, 18, 16],
    garbage:     [25, 22, 28, 30, 32, 28],
    drainage:    [8, 6, 15, 22, 35, 38],
    electricity: [15, 12, 18, 20, 22, 19],
  }
};

// ---- District Stats ----
export const DISTRICT_STATS = [
  { name: 'Central',  reported: 45, resolved: 38, inProgress: 5,  population: 320000 },
  { name: 'East',     reported: 62, resolved: 48, inProgress: 9,  population: 480000 },
  { name: 'West',     reported: 38, resolved: 32, inProgress: 4,  population: 290000 },
  { name: 'South',    reported: 55, resolved: 42, inProgress: 8,  population: 410000 },
  { name: 'North',    reported: 41, resolved: 35, inProgress: 4,  population: 370000 },
  { name: 'RR Nagar', reported: 28, resolved: 22, inProgress: 4,  population: 250000 },
  { name: 'Bommanahalli', reported: 33, resolved: 26, inProgress: 5, population: 310000 },
  { name: 'Mahadevapura', reported: 57, resolved: 44, inProgress: 8, population: 450000 },
  { name: 'Yelahanka', reported: 22, resolved: 18, inProgress: 3, population: 220000 },
];

// ---- Application State ----
export const AppState = {
  currentUser: {
    name: 'You',
    avatar: 'YO',
    level: 4,
    xp: 720,
    issuesReported: 8,
    issuesVerified: 12,
    currentStreak: 5,
    badges: ['first_report', 'reporter_5', 'verifier_5'],
  },
  issues: [...SAMPLE_ISSUES],
  filters: {
    category: 'all',
    status: 'all',
    priority: 'all',
    search: '',
  },
  selectedIssue: null,
  mapInstance: null,
  chartInstances: {},
};
